version: '3.1'

services:
  go:
    image: debian
    restart: unless-stopped
    ports:
      - "1369:3000"
    volumes:
      - .:/home/go/app
    networks:
      - app-network
    command: /home/go/app/server
    links:
      - mongo:mongo
  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
