version: '3.1'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: debian
    restart: unless-stopped
    ports:
      - ":3000"
    volumes:
      - .:/home/go/app
    networks:
      - app-network
    command: .\server
  mongo:
    image: mongo
    restart: always
    ports:
      - ":27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mohamed
      MONGO_INITDB_ROOT_PASSWORD: test

networks:
  app-network:
    driver: bridge